openapi: 3.2.0
info:
  title: Skore Hub Liveness API
  description: 'This REST API is divided in small services.

    Each service has its own OpenAPI specification.

    - identity

    - projects'
  version: 0.1.0
tags:
- name: Liveness
paths:
  /liveness:
    get:
      summary: Liveness
      description: 'Expose liveness probe.


        This endpoint checks the liveness of the application and returns version

        information.


        Returns

        -------

        dict: A dictionary containing version information.'
      operationId: liveness_liveness_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Liveness Liveness Get
      tags:
      - Liveness
